export type {
  AgentAudition,
  AgentDefinition,
  AgentAssignment,
  AgentRegistryEntry,
  AgentRegistrySnapshot,
  ExpertisePack,
  ExpertisePackRef,
  KnowledgeMethod,
  KnowledgePacket,
  KnowledgeSource,
  ExperienceObservation,
  LocalHardwareInventory,
  LocalModel,
  LocalModelInventory,
  ModelBenchmark,
  ModelRouteCandidate,
  ModelRoutingRecord,
  RecruitmentRecord,
} from "@gameagent/protocol";
